SELECT
    id as drg_id,
    comment as drg_comment,                      
    ron_entry as drg_ronentry,
    created_at as drg_created_at,
    deceased_id as drg_deceasedid,
    entry_number as drg_entrynumber,
    informant_id as drg_informantid,
    mccd_case_id as drg_mccd_case_id,
    register_number as drg_registernumber,
    registration_id as drg_registrationid,
    registration_date as drg_registrationdate,
    informant_signature as drg_informantsignature,
    owner_place_details as drg_ownerplacedetails,
    registered_manually as drg_registeredmanually,
    registrar_signature as drg_registrarsignature,
    registrar_designation as drg_registrardesignation,
    bilingual_registration as drg_bilingualregistration,
    ind_rg_authority_given as drg_indrgauthoritygiven,
    declare_out_of_district as drg_declareoutofdistrict,
    register_after_five_days as drg_registerafterfivedays,
    registration_place_details as drg_registrationplacedetails,
    on_rg_authority_text_required as drg_onrgauthoritytextrequired,
    registration_place_details_id as drg_registrationplacedetailsid
FROM {{ source('application_raw_data', 'death_registration_record') }} 