SELECT
    id,
    comment,                      
    ron_entry as ronentry,
    created_at as createdat,
    deceased_id as deceasedid,
    entry_number as entrynumber,
    informant_id as informantid,
    mccd_case_id as mccdcaseid,
    register_number as registernumber,
    registration_id as registrationid,
    registration_date as registrationdate,
    owner_place_details as ownerplacedetails,
    registered_manually as registeredmanually,
    registrar_signature as registrarsignature,
    registrar_designation as registrardesignation,
    bilingual_registration as bilingualregistration,
    ind_rg_authority_given as indrgauthoritygiven,
    declare_out_of_district as declareoutofdistrict,
    register_after_five_days as registerafterfivedays,
    registration_place_details as registrationplacedetails,
    on_rg_authority_text_required as onrgauthoritytextrequired,
    registration_place_details_id as registrationplacedetailsid
FROM {{ source('application_raw_data', 'death_registration_record') }} 